### ISSUE TITLE
Non determenistic behavior

### ISSUE THREAD

**Issue by favetelinguis** [jarohen/chime#13]
I have noticed that the schedular is not determenistic, for example using the code shown like so from the repl:
```
(def s (start 3000))
(s)
```
And then redo this ~10 times in the repl the following behavior will be observed:
Somethimes "Trigger 0" will be shown right away and sometimes nothing will be shown.

The expected behavior i would like on every restart is that NO value should be shown until after 3000sec after the most current restart.
```
(ns hello-world.c
  (:require
   [clojure.core.async :as a :refer (<! go-loop)]
   [chime :refer (chime-ch)]
   [clj-time.core :as t]
   [clj-time.periodic :refer (periodic-seq)]
   ))

(defn start
  [keep-alive-period]
  (let [timer-ch (chime-ch (periodic-seq (t/now)
                                         (-> keep-alive-period t/seconds)))]
    (go-loop [i 0]
      (when-let [trigger-time (<! timer-ch)]
        (println "Trigger: " i)
        (recur (inc i))))
    (fn stop-fn [] (a/close! timer-ch))))
```

**Comment by jarohen** [comment]
Hi there, thanks for getting in touch :)

This behaviour is because Chime removes any times in the past when starting a schedule - this is so that, for example, you can start a 6am daily schedule at any time of day with `(periodic-seq (t/today-at 6 0) (t/days 1))`. without worrying about whether it's been 6am today already. Chime also (because of joda-time) resolves times to the nearest millisecond - so the 'non-determinism' you're seeing here is because of the time difference between your call to `(t/now)` and Chime's check for times in the past. If this occurs over a millisecond boundary, you won't see the message - if it doesn't, you will.

In your case, though, if you don't want an occurrence immediately, you can remove `(t/now)` from the `periodic-seq` - i.e. `(chime-ch (rest (periodic-seq ...)))` - let me know if this fits your use case!

I should probably document this though, thanks :)

James

**Comment by favetelinguis** [comment]
Thanks for the help. Your library fits my usecase very well so far, this is the only things that has been bugging me so woulc be nice to get rid of this :)

Would you mind showing an example, not sure how to use periodic-seq:
```
(chime-ch (rest (periodic-seq #_(t/now)
                                               (-> 5 t/seconds))))
```

Throws to few arguments to periodic-seq and the docs says i need a start time so not sure i understand what you are suggesting.

**Comment by jarohen** [comment]
Sorry, my message was unclear: `(t/now)` is the first value in the sequence returned by `periodic-seq`, so the `rest` removes it:

`(chime-ch (rest (periodic-seq (t/now) (t/seconds 5))))`

**Comment by favetelinguis** [comment]
Nice that solved it! Thanks
